import React, { createContext, useCallback, useContext, useEffect, useMemo, useState } from 'react';

export type Language = 'en' | 'ne';

interface LanguageContextValue {
  language: Language;
  setLanguage: (language: Language) => void;
  toggleLanguage: () => void;
  t: (key: string, fallback?: string) => string;
}

const STORAGE_KEY = 'gauhatt_language';

const translations: Record<Language, Record<string, string>> = {
  en: {
    'language.current': 'English',
    'language.switchTo': 'Switch to Nepali',
    'nav.home': 'Home',
    'nav.products': 'Products',
    'nav.cart': 'Cart',
    'nav.explore': 'Explore',
    'nav.orders': 'My Orders',
    'nav.notifications': 'Notifications',
    'auth.signIn': 'Sign In',
    'auth.logout': 'Logout',
    'search.global': 'Search for local products or shops...',
    'search.mobile': 'Search for local products...',
    'notifications.title': 'Notifications',
    'notifications.markAllRead': 'Mark all read',
    'notifications.loading': 'Loading...',
    'notifications.empty': 'No notifications yet',
    'notifications.viewAll': 'View all notifications',
    'sidebar.browseCategories': 'Browse Categories',
    'sidebar.filters': 'Filters',
    'sidebar.deliveryRadius': 'Delivery Radius',
    'category.vegetables': 'Vegetables',
    'category.dairyEggs': 'Dairy & Eggs',
    'category.fruits': 'Fruits',
    'category.bakedGoods': 'Baked Goods',
    'category.pantry': 'Pantry',
    'category.handmadeCrafts': 'Handmade Crafts',
    'category.cookingEssentials': 'Cooking Essentials',
    'category.floralPlants': 'Floral & Plants',
    'home.freshFromLocalFarms': 'Fresh from Local Farms',
    'home.farmFreshDeliveredDaily': 'Farm Fresh, Delivered Daily',
    'home.heroDescription': 'Experience the finest organic produce, dairy, and artisanal goods, sourced directly from farmers within your community.',
    'home.featuredProducts': 'Featured Products',
    'home.handpickedForYou': 'Handpicked selections tailored for you',
    'home.exploreNearby': 'Explore Nearby',
    'home.category': 'Category',
    'home.minPriceRs': 'Min Price (Rs)',
    'home.maxPriceRs': 'Max Price (Rs)',
    'home.sortBy': 'Sort By',
    'home.organicOnly': 'Organic only',
    'home.reset': 'Reset',
    'home.noExploreResults': 'No products match your explore filters.',
    'home.tryAdjustFilters': 'Try changing category, price, or organic filter.',
    'home.shoppingCart': 'Shopping Cart',
    'home.summary': 'Summary',
    'home.subtotal': 'Subtotal',
    'home.delivery': 'Delivery',
    'home.calculatedAtCheckout': 'Calculated at checkout',
    'home.total': 'Total',
    'home.proceedToCheckout': 'Proceed to Checkout',
    'home.noProductsMatch': 'No products match your filters.',
    'home.searchFarmsProducts': 'Search farms, products...',
    'home.startShopping': 'Start Shopping',
    'home.cartIsEmpty': 'Cart is empty',
    'home.noActiveOrders': 'No active orders',
    'home.noRecentOrders': "You haven't ordered anything recently.",
    'home.allCaughtUp': "You're all caught up!",
    'home.noNotifications': 'No new notifications right now.',
    'home.rate': 'Rate',
    'home.update': 'Update',
    'landing.products': 'Products',
    'landing.getStarted': 'Get Started',
    'landing.topText': 'Farm Fresh, Delivered Daily',
    'landing.mainText': 'Farm to Table',
    'landing.subText': 'Connect directly with local farmers. Fresh, organic vegetables delivered to your doorstep in under 24 hours. Skip the middleman, support farmers, eat healthier.',
    'landing.enterDistrict': 'Enter your district (e.g. Kathmandu)...',
    'landing.check': 'Check',
    'landing.serviceAvailable': 'Service is available in',
    'landing.comingSoonTo': 'Coming soon to',
    'landing.joinNotified': 'Join to get notified!',
    'landing.currentlyServing': 'Currently serving 10+ major districts',
    'landing.whyChoose': 'Why Choose Gauhatt?',
    'landing.whyChooseDesc': 'We combine modern technology with traditional farming values to bring you a transparent, fair, and incredibly fresh food system.',
    'auth.welcomeBack': 'Welcome Back!',
    'auth.enterCredentials': 'Enter your credentials to access your account.',
    'auth.emailOrUsername': 'Email or Username',
    'auth.password': 'Password',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.login': 'Login',
    'auth.createAccount': 'Create an account',
    'auth.termsPrefix': 'By continuing, you agree to GAUHATT\'s',
    'auth.terms': 'Terms of Service',
    'auth.and': 'and',
    'auth.privacy': 'Privacy Policy',
    'otp.verifyEmail': 'Verify Your Email Address',
    'otp.sentCodeTo': "We've sent a 6 digit code to",
    'otp.enterSixDigit': 'Please enter complete 6-digit code',
    'otp.invalidCode': 'Invalid verification code.',
    'otp.verifiedRedirect': 'Email verified successfully! Redirecting to login...',
    'otp.verifyFailed': 'Verification failed. Please try again.',
    'otp.resend': 'Resend OTP',
    'otp.sending': 'Sending...',
    'otp.verify': 'Verify OTP',
    'otp.backToRegistration': 'Back to registration',
    'intro.skip': 'Skip',
    'intro.next': 'Next',
    'common.or': 'OR',
    'common.back': 'Back',
    'common.submitting': 'Submitting...',
    'common.updating': 'Updating...',
    'register.title': 'Create an Account',
    'register.subtitle': 'Join our community of sustainable food.',
    'register.role.consumer': 'Consumer',
    'register.role.farmer': 'Farmer',
    'register.role.delivery': 'Delivery',
    'register.step.account': 'Account',
    'register.step.farmInfo': 'Farm Info',
    'register.step.details': 'Details',
    'register.username': 'Username',
    'register.email': 'Email address',
    'register.password': 'Password',
    'register.confirmPassword': 'Confirm Password',
    'register.yourLocation': 'Your Location',
    'register.locationSet': 'Location Set',
    'register.update': 'Update',
    'register.gettingLocation': 'Getting location...',
    'register.setMyLocation': 'Set My Location',
    'register.locationHint': 'Location is required for delivery calculations (within 40km range)',
    'register.farmName': 'Farm Name',
    'register.selectDistrict': 'Select District',
    'register.farmAddress': 'Complete farm address',
    'register.cropType': 'Crop Type',
    'register.crop.vegetables': 'Vegetables',
    'register.crop.grain': 'Grain',
    'register.crop.fruits': 'Fruits',
    'register.crop.pulses': 'Pulses',
    'register.farmPhoto': 'Farm Photo',
    'register.identityProof': 'Identity Proof',
    'register.phone': 'Phone Number (10 digits)',
    'register.fullName': 'Full Name',
    'register.vehicleType': 'Select Vehicle Type',
    'register.vehicleNumber': 'Vehicle Number (Optional)',
    'register.nextStep': 'Next Step',
    'register.createAccount': 'Create Account',
    'register.submit': 'Register',
    'register.alreadyHaveAccount': 'Already have an account?',
    'register.signIn': 'sign in',
    'register.error.locationAccess': 'Unable to get location. Please allow location access.',
    'register.error.usernameRequired': 'Username is required',
    'register.error.invalidEmail': 'Invalid email address',
    'register.error.passwordRequired': 'Password is required',
    'register.error.passwordRules': 'Password must be 6+ chars with 1 special character',
    'register.error.passwordMismatch': 'Passwords do not match',
    'register.error.locationRequired': 'Location is required. Please set your location.',
    'register.error.farmNameRequired': 'Farm Name is required',
    'register.error.locationRequiredShort': 'Location is required',
    'register.error.addressRequired': 'Address is required',
    'register.error.phoneDigits': 'Phone number must be 10 digits',
    'register.error.fullNameRequired': 'Full name is required',
    'register.error.vehicleTypeRequired': 'Vehicle type is required',
    'register.error.validationFailed': 'Validation failed',
    'register.error.registrationFailed': 'Registration failed',
    'checkout.error.consumerOnly': 'Only consumers can place orders. Please log in with a consumer account.',
    'checkout.error.fullNameRequired': 'Full name is required',
    'checkout.error.phoneRequired': 'Phone number is required',
    'checkout.error.phoneInvalid': 'Enter a valid 10-digit phone number',
    'checkout.error.addressRequired': 'Delivery address is required',
    'checkout.error.cityRequired': 'City/District is required',
    'checkout.error.placeOrderFailed': 'Failed to place order. Please try again.',
    'checkout.error.sessionExpired': 'Your session has expired. Please log in again.',
    'checkout.error.loginRequired': 'Please log in to place an order.',
    'checkout.error.connectionFailed': 'Failed to place order. Please check your connection and try again.',
    'checkout.success.title': 'Order Placed Successfully!',
    'checkout.success.subtitle': "Thank you for your order. We'll contact you shortly to confirm.",
    'checkout.success.orderId': 'Order ID',
    'checkout.success.paymentMethod': 'Payment Method',
    'checkout.success.totalAmount': 'Total Amount',
    'checkout.success.includesDelivery': 'Includes delivery',
    'checkout.success.estimatedDelivery': 'Estimated Delivery',
    'checkout.success.deliveryWindow': 'Within 24-48 hours',
    'checkout.success.continueShopping': 'Continue Shopping',
    'checkout.success.goHome': 'Go to Home',
    'checkout.backToCart': 'Back to Cart',
    'checkout.deliveryDetails': 'Delivery Details',
    'checkout.fullName': 'Full Name',
    'checkout.fullNamePlaceholder': 'Enter your full name',
    'checkout.phoneNumber': 'Phone Number',
    'checkout.phonePlaceholder': '10-digit phone number',
    'checkout.deliveryAddress': 'Delivery Address',
    'checkout.addressPlaceholder': 'House/Flat No., Street, Area',
    'checkout.cityDistrict': 'City / District',
    'checkout.cityPlaceholder': 'e.g., Kathmandu, Lalitpur',
    'checkout.landmark': 'Landmark (Optional)',
    'checkout.landmarkPlaceholder': 'Nearby landmark for easy delivery',
    'checkout.deliveryNotes': 'Delivery Notes (Optional)',
    'checkout.notesPlaceholder': 'Any special instructions for delivery',
    'checkout.paymentMethod': 'Payment Method',
    'checkout.cashOnDelivery': 'Cash on Delivery',
    'checkout.payOnDelivery': 'Pay when your order is delivered',
    'checkout.orderFailed': 'Order Failed',
    'checkout.placingOrder': 'Placing Order...',
    'checkout.placeOrder': 'Place Order',
    'checkout.orderSummary': 'Order Summary',
    'checkout.qty': 'Qty',
    'checkout.subtotal': 'Subtotal',
    'checkout.deliveryFee': 'Delivery Fee',
    'checkout.breakdownByFarm': 'Breakdown by farm:',
    'checkout.beyondLimit': 'Some items cannot be delivered (beyond 40km limit)',
    'checkout.total': 'Total',
    'checkout.includingDelivery': 'Including delivery charges',
    'checkout.deliveryLocationRequired': 'Delivery location required',
    'checkout.removeBeyondLimit': 'Remove items beyond 40km to proceed',
    'checkout.payOnReceive': 'Pay when you receive your order',
    'checkout.deliveryPricing': 'Delivery Pricing',
    'checkout.deliveryPricingRule': 'NPR 50 per 10km (rounded up)',
    'products.location.permissionDenied': 'Location permission denied. Please enable location access or enter manually.',
    'products.location.unableDetermine': 'Unable to determine your location. Please enter manually.',
    'products.location.timeout': 'Location request timed out. Please try again or enter manually.',
    'products.location.failedGet': 'Failed to get location. Please enter manually.',
    'products.location.validCoordinates': 'Please enter valid coordinates',
    'products.location.latitudeRange': 'Latitude must be between -90 and 90',
    'products.location.longitudeRange': 'Longitude must be between -180 and 180',
    'products.location.requiredTitle': '📍 Location Required',
    'products.location.setTitle': 'Set Your Location',
    'products.location.requiredDesc': 'Please set your location to browse products. This helps us show you farms near you and calculate accurate delivery fees.',
    'products.location.setDesc': 'We need your location to calculate delivery fees and show products available in your area.',
    'products.addingToCart': 'Adding to cart...',
    'products.location.getting': 'Getting Location...',
    'products.location.allowAccess': 'Allow Location Access',
    'products.location.enterManually': 'Enter Location Manually',
    'products.location.storedLocally': 'Your location is stored locally and used only for delivery calculations.',
    'products.location.latitude': 'Latitude',
    'products.location.longitude': 'Longitude',
    'products.location.addressOptional': 'Address (Optional)',
    'products.location.tip': 'Tip: Find coordinates on Google Maps by right-clicking and selecting "What\'s here?"',
    'products.location.setLocation': 'Set Location',
    'products.rateProduct': 'Rate',
    'products.rateQuestion': 'How would you rate this product?',
    'products.rating.tapToRate': 'Tap a star fruit to rate',
    'products.rating.1': 'Not Fresh 😕',
    'products.rating.2': 'Okay 🙂',
    'products.rating.3': 'Tasty 😋',
    'products.rating.4': 'Delicious 😍',
    'products.rating.5': 'Farm Fresh! 🤤',
    'products.writeReviewOptional': 'Write a review (optional)',
    'products.reviewPlaceholder': 'Share your experience with this product...',
    'products.signInToRate': 'Please sign in to submit your rating',
    'products.submitRating': 'Submit Rating',
    'products.by': 'By',
    'products.watchVideo': 'Watch Video',
    'products.comments': 'comments',
    'products.commentsTitle': 'Comments',
    'products.addComment': 'Add a comment...',
    'products.noComments': 'No comments yet. Be the first!',
    'products.organic': 'Organic',
    'products.story': 'Story',
    'products.stories': 'Stories',
    'products.rateThisProduct': 'Rate this product',
    'products.rate': 'Rate',
    'products.sort.newest': 'Newest Arrivals',
    'products.sort.priceLow': 'Price: Low to High',
    'products.sort.priceHigh': 'Price: High to Low',
    'products.sort.distance': 'Distance: Nearest',
    'products.sort.name': 'Name: A-Z',
    'products.deliveryLocationSet': 'Delivery Location Set',
    'products.setLocationBetter': '📍 Set Your Location for Better Experience',
    'products.showingWithin': 'Showing farms within',
    'products.accurateDeliveryAndNearby': 'Get accurate delivery fees & see products near you',
    'products.maxDistance': 'Max Distance:',
    'products.allProducts': 'All Products',
    'products.showing': 'Showing',
    'products.of': 'of',
    'products.products': 'products',
    'products.search': 'Search...',
    'products.noProductsHint': "Try adjusting your filters or search terms to find what you're looking for",
    'products.clearAllFilters': 'Clear all filters',
    'delivery.error.loadData': 'Failed to load data',
    'delivery.error.updateAvailability': 'Failed to update availability',
    'delivery.error.updateStatus': 'Failed to update status',
    'delivery.error.updateLocation': 'Failed to update location. Please allow location access.',
    'delivery.tab.dashboard': 'Dashboard',
    'delivery.tab.assignments': 'Assignments',
    'delivery.tab.profile': 'Profile',
    'delivery.welcomeBack': 'Welcome back',
    'delivery.welcomeDesc': 'Track assignments, manage your availability, and keep deliveries on time.',
    'delivery.setUnavailable': 'Set Unavailable',
    'delivery.setAvailable': 'Set Available',
    'delivery.assignmentDistanceNote': 'Assignments are dispatched by distance within 50 km',
    'delivery.updateLocation': 'Update Location',
    'delivery.pending': 'Pending',
    'delivery.active': 'Active',
    'delivery.completed': 'Completed',
    'delivery.earnings': 'Earnings',
    'delivery.todaySummary': "Today's Summary",
    'delivery.deliveriesToday': 'Deliveries Today',
    'delivery.earningsToday': 'Earnings Today',
    'delivery.overallStats': 'Overall Statistics',
    'admin.tab.overview': 'Overview',
    'admin.tab.orders': 'Orders',
    'admin.tab.users': 'Users',
    'admin.tab.farmerApprovals': 'Farmer Approvals',
    'admin.tab.topProducts': 'Top Products',
    'admin.tab.analytics': 'Analytics',
    'admin.refreshData': 'Refresh Data',
    'admin.administrator': 'Administrator',
    'admin.updatedAt': 'Updated',
    'productDetails.invalidId': 'Invalid product id.',
    'productDetails.unableOpen': 'Unable to open product',
    'productDetails.notFound': 'Product not found.',
    'productDetails.loadFailed': 'Failed to load product details.',
    'productDetails.unavailable': 'This product is unavailable.',
    'productDetails.backToProducts': 'Back to products',
    'productDetails.noDescription': 'No description available yet for this product.',
    'productDetails.reviews': 'reviews',
    'productDetails.farmer': 'Farmer',
    'productDetails.farm': 'Farm',
    'productDetails.kmAway': 'km away',
    'productDetails.addToCart': 'Add to cart',
    'productDetails.customerReviews': 'Customer Reviews',
    'productDetails.noReviews': 'No reviews yet. Be the first to rate this product.',
    'discover.loadingProducts': 'Loading Products',
    'discover.freshProducts': 'Fresh Products',
    'discover.noProductsYet': 'No Products Yet',
    'discover.description': 'This is a dedicated product preview page from the landing navigation. Browse quickly, then open the full products page for filters and location-based delivery details.',
    'discover.noProductsAvailable': 'No products are available right now.',
    'discover.buyNow': 'Buy Now',
    'consumer.notAssigned': 'Not Assigned',
    'consumer.pickedUp': 'Picked Up',
    'consumer.inTransit': 'In Transit',
    'consumer.welcomeTitle': 'Welcome to Consumer Page',
    'consumer.hello': 'Hello',
    'consumer.deliveryInfo': 'Delivery Info',
    'consumer.viewAllOrders': 'View all orders',
    'consumer.noDeliveryUpdates': 'No delivery updates yet.',
    'consumer.partner': 'Partner',
    'consumer.partnerNotAssigned': 'Partner not assigned',
  },
  ne: {
    'language.current': 'नेपाली',
    'language.switchTo': 'अंग्रेजीमा बदल्नुहोस्',
    'nav.home': 'होम',
    'nav.products': 'उत्पादनहरू',
    'nav.cart': 'कार्ट',
    'nav.explore': 'अन्वेषण',
    'nav.orders': 'मेरो अर्डरहरू',
    'nav.notifications': 'सूचनाहरू',
    'auth.signIn': 'साइन इन',
    'auth.logout': 'लगआउट',
    'search.global': 'स्थानीय उत्पादन वा पसल खोज्नुहोस्...',
    'search.mobile': 'स्थानीय उत्पादन खोज्नुहोस्...',
    'notifications.title': 'सूचनाहरू',
    'notifications.markAllRead': 'सबै पढिएको चिन्ह लगाउनुहोस्',
    'notifications.loading': 'लोड हुँदैछ...',
    'notifications.empty': 'अहिलेसम्म कुनै सूचना छैन',
    'notifications.viewAll': 'सबै सूचनाहरू हेर्नुहोस्',
    'sidebar.browseCategories': 'श्रेणीहरू ब्राउज गर्नुहोस्',
    'sidebar.filters': 'फिल्टरहरू',
    'sidebar.deliveryRadius': 'डेलिभरी दूरी',
    'category.vegetables': 'तरकारी',
    'category.dairyEggs': 'दुग्ध र अण्डा',
    'category.fruits': 'फलफूल',
    'category.bakedGoods': 'बेकरी सामान',
    'category.pantry': 'प्यान्ट्री',
    'category.handmadeCrafts': 'हाते हस्तकला',
    'category.cookingEssentials': 'खाना पकाउने सामग्री',
    'category.floralPlants': 'फूल र बोटबिरुवा',
    'home.freshFromLocalFarms': 'स्थानीय फार्मबाट ताजा',
    'home.farmFreshDeliveredDaily': 'फार्मको ताजा उत्पादन, दैनिक डेलिभरी',
    'home.heroDescription': 'तपाईंको समुदायका किसानबाट सिधै ल्याइएका उत्कृष्ट अर्गानिक उत्पादन, दुग्ध र हस्तकला सामग्री अनुभव गर्नुहोस्।',
    'home.featuredProducts': 'विशेष उत्पादनहरू',
    'home.handpickedForYou': 'तपाईंका लागि छनोट गरिएका',
    'home.exploreNearby': 'नजिकका उत्पादन अन्वेषण',
    'home.category': 'श्रेणी',
    'home.minPriceRs': 'न्यूनतम मूल्य (रु)',
    'home.maxPriceRs': 'अधिकतम मूल्य (रु)',
    'home.sortBy': 'क्रमबद्ध गर्ने',
    'home.organicOnly': 'अर्गानिक मात्र',
    'home.reset': 'रिसेट',
    'home.noExploreResults': 'तपाईंका फिल्टरसँग मेल खाने उत्पादन भेटिएन।',
    'home.tryAdjustFilters': 'श्रेणी, मूल्य वा अर्गानिक फिल्टर परिवर्तन गरी हेर्नुहोस्।',
    'home.shoppingCart': 'किनमेल कार्ट',
    'home.summary': 'सारांश',
    'home.subtotal': 'उप-जम्मा',
    'home.delivery': 'डेलिभरी',
    'home.calculatedAtCheckout': 'चेकआउटमा गणना हुन्छ',
    'home.total': 'जम्मा',
    'home.proceedToCheckout': 'चेकआउटमा जानुहोस्',
    'home.noProductsMatch': 'तपाईंका फिल्टरसँग मेल खाने उत्पादन छैन।',
    'home.searchFarmsProducts': 'फार्म वा उत्पादन खोज्नुहोस्...',
    'home.startShopping': 'किनमेल सुरु गर्नुहोस्',
    'home.cartIsEmpty': 'कार्ट खाली छ',
    'home.noActiveOrders': 'सक्रिय अर्डर छैन',
    'home.noRecentOrders': 'तपाईंले हालै कुनै अर्डर गर्नुभएको छैन।',
    'home.allCaughtUp': 'तपाईं सबै अपडेटमा हुनुहुन्छ!',
    'home.noNotifications': 'अहिले नयाँ सूचना छैन।',
    'home.rate': 'मूल्याङ्कन',
    'home.update': 'अपडेट',
    'landing.products': 'उत्पादनहरू',
    'landing.getStarted': 'सुरु गर्नुहोस्',
    'landing.topText': 'फार्मको ताजा उत्पादन, दैनिक डेलिभरी',
    'landing.mainText': 'फार्मदेखि टेबलसम्म',
    'landing.subText': 'स्थानीय किसानसँग सिधै जडान हुनुहोस्। २४ घण्टाभित्र ताजा अर्गानिक तरकारी घरमै पाउनुहोस्। बिचौलिया हटाउनुहोस्, किसानलाई साथ दिनुहोस्, स्वस्थ खानुहोस्।',
    'landing.enterDistrict': 'आफ्नो जिल्ला लेख्नुहोस् (जस्तै: काठमाडौं)...',
    'landing.check': 'जाँच',
    'landing.serviceAvailable': 'सेवा उपलब्ध छ',
    'landing.comingSoonTo': 'छिट्टै आउँदैछ',
    'landing.joinNotified': 'सूचना पाउन अहिले नै जोडिनुहोस्!',
    'landing.currentlyServing': 'हाल १०+ प्रमुख जिल्लामा सेवा उपलब्ध',
    'landing.whyChoose': 'किन Gauhatt रोज्ने?',
    'landing.whyChooseDesc': 'हामी आधुनिक प्रविधि र पारम्परिक खेतीका मूल्य मिलाएर पारदर्शी, न्यायपूर्ण र अत्यन्त ताजा खाद्य प्रणाली ल्याउँछौं।',
    'auth.welcomeBack': 'फेरि स्वागत छ!',
    'auth.enterCredentials': 'आफ्नो खाता खोल्न विवरण प्रविष्ट गर्नुहोस्।',
    'auth.emailOrUsername': 'इमेल वा प्रयोगकर्ता नाम',
    'auth.password': 'पासवर्ड',
    'auth.forgotPassword': 'पासवर्ड बिर्सनुभयो?',
    'auth.login': 'लगइन',
    'auth.createAccount': 'नयाँ खाता बनाउनुहोस्',
    'auth.termsPrefix': 'अगाडि बढेर तपाईं GAUHATT का',
    'auth.terms': 'सेवा सर्तहरू',
    'auth.and': 'र',
    'auth.privacy': 'गोपनीयता नीति',
    'otp.verifyEmail': 'आफ्नो इमेल प्रमाणित गर्नुहोस्',
    'otp.sentCodeTo': 'हामीले ६ अङ्कको कोड पठाएका छौं',
    'otp.enterSixDigit': 'कृपया पूरा ६ अङ्कको कोड लेख्नुहोस्',
    'otp.invalidCode': 'प्रमाणीकरण कोड गलत छ।',
    'otp.verifiedRedirect': 'इमेल सफलतापूर्वक प्रमाणित भयो! लगइनमा पठाउँदैछ...',
    'otp.verifyFailed': 'प्रमाणीकरण असफल भयो। फेरि प्रयास गर्नुहोस्।',
    'otp.resend': 'OTP फेरि पठाउनुहोस्',
    'otp.sending': 'पठाउँदै...',
    'otp.verify': 'OTP प्रमाणित गर्नुहोस्',
    'otp.backToRegistration': 'दर्तामा फर्कनुहोस्',
    'intro.skip': 'छोड्नुहोस्',
    'intro.next': 'अर्को',
    'common.or': 'वा',
    'common.back': 'फिर्ता',
    'common.submitting': 'पेश हुँदैछ...',
    'common.updating': 'अपडेट हुँदैछ...',
    'register.title': 'खाता बनाउनुहोस्',
    'register.subtitle': 'दिगो खानाका लागि हाम्रो समुदायमा सामेल हुनुहोस्।',
    'register.role.consumer': 'उपभोक्ता',
    'register.role.farmer': 'किसान',
    'register.role.delivery': 'डेलिभरी',
    'register.step.account': 'खाता',
    'register.step.farmInfo': 'फार्म विवरण',
    'register.step.details': 'विवरण',
    'register.username': 'प्रयोगकर्ता नाम',
    'register.email': 'इमेल ठेगाना',
    'register.password': 'पासवर्ड',
    'register.confirmPassword': 'पासवर्ड पुष्टि गर्नुहोस्',
    'register.yourLocation': 'तपाईंको स्थान',
    'register.locationSet': 'स्थान सेट भयो',
    'register.update': 'अपडेट',
    'register.gettingLocation': 'स्थान लिंदैछ...',
    'register.setMyLocation': 'मेरो स्थान सेट गर्नुहोस्',
    'register.locationHint': 'डेलिभरी गणनाका लागि स्थान आवश्यक छ (४० किमि भित्र)',
    'register.farmName': 'फार्मको नाम',
    'register.selectDistrict': 'जिल्ला छान्नुहोस्',
    'register.farmAddress': 'पूरा फार्म ठेगाना',
    'register.cropType': 'बाली प्रकार',
    'register.crop.vegetables': 'तरकारी',
    'register.crop.grain': 'अन्न',
    'register.crop.fruits': 'फलफूल',
    'register.crop.pulses': 'दलहन',
    'register.farmPhoto': 'फार्म फोटो',
    'register.identityProof': 'पहिचान प्रमाण',
    'register.phone': 'फोन नम्बर (१० अंक)',
    'register.fullName': 'पूरा नाम',
    'register.vehicleType': 'सवारी साधनको प्रकार छान्नुहोस्',
    'register.vehicleNumber': 'सवारी नम्बर (वैकल्पिक)',
    'register.nextStep': 'अर्को चरण',
    'register.createAccount': 'खाता बनाउनुहोस्',
    'register.submit': 'दर्ता गर्नुहोस्',
    'register.alreadyHaveAccount': 'पहिले नै खाता छ?',
    'register.signIn': 'साइन इन',
    'register.error.locationAccess': 'स्थान प्राप्त गर्न सकेन। कृपया स्थान पहुँच अनुमति दिनुहोस्।',
    'register.error.usernameRequired': 'प्रयोगकर्ता नाम आवश्यक छ',
    'register.error.invalidEmail': 'अवैध इमेल ठेगाना',
    'register.error.passwordRequired': 'पासवर्ड आवश्यक छ',
    'register.error.passwordRules': 'पासवर्ड कम्तीमा ६ अक्षर र १ विशेष चिन्ह हुनुपर्छ',
    'register.error.passwordMismatch': 'पासवर्ड मिलेन',
    'register.error.locationRequired': 'स्थान आवश्यक छ। कृपया आफ्नो स्थान सेट गर्नुहोस्।',
    'register.error.farmNameRequired': 'फार्मको नाम आवश्यक छ',
    'register.error.locationRequiredShort': 'स्थान आवश्यक छ',
    'register.error.addressRequired': 'ठेगाना आवश्यक छ',
    'register.error.phoneDigits': 'फोन नम्बर १० अंकको हुनुपर्छ',
    'register.error.fullNameRequired': 'पूरा नाम आवश्यक छ',
    'register.error.vehicleTypeRequired': 'सवारी प्रकार आवश्यक छ',
    'register.error.validationFailed': 'मान्यकरण असफल भयो',
    'register.error.registrationFailed': 'दर्ता असफल भयो',
    'checkout.error.consumerOnly': 'अर्डर राख्न केवल उपभोक्ताले मात्र सक्छन्। कृपया उपभोक्ता खाताबाट लगइन गर्नुहोस्।',
    'checkout.error.fullNameRequired': 'पूरा नाम आवश्यक छ',
    'checkout.error.phoneRequired': 'फोन नम्बर आवश्यक छ',
    'checkout.error.phoneInvalid': 'मान्य १० अङ्कको फोन नम्बर लेख्नुहोस्',
    'checkout.error.addressRequired': 'डेलिभरी ठेगाना आवश्यक छ',
    'checkout.error.cityRequired': 'सहर/जिल्ला आवश्यक छ',
    'checkout.error.placeOrderFailed': 'अर्डर राख्न असफल भयो। फेरि प्रयास गर्नुहोस्।',
    'checkout.error.sessionExpired': 'तपाईंको सत्र समाप्त भयो। कृपया पुन: लगइन गर्नुहोस्।',
    'checkout.error.loginRequired': 'अर्डर राख्न लगइन गर्नुहोस्।',
    'checkout.error.connectionFailed': 'अर्डर राख्न असफल भयो। नेटवर्क जाँचेर फेरि प्रयास गर्नुहोस्।',
    'checkout.success.title': 'अर्डर सफलतापूर्वक राखियो!',
    'checkout.success.subtitle': 'तपाईंको अर्डरको लागि धन्यवाद। पुष्टि गर्न छिट्टै सम्पर्क गर्नेछौं।',
    'checkout.success.orderId': 'अर्डर आईडी',
    'checkout.success.paymentMethod': 'भुक्तानी विधि',
    'checkout.success.totalAmount': 'कुल रकम',
    'checkout.success.includesDelivery': 'डेलिभरी समावेश',
    'checkout.success.estimatedDelivery': 'अनुमानित डेलिभरी',
    'checkout.success.deliveryWindow': '२४-४८ घण्टा भित्र',
    'checkout.success.continueShopping': 'किनमेल जारी राख्नुहोस्',
    'checkout.success.goHome': 'होममा जानुहोस्',
    'checkout.backToCart': 'कार्टमा फिर्ता',
    'checkout.deliveryDetails': 'डेलिभरी विवरण',
    'checkout.fullName': 'पूरा नाम',
    'checkout.fullNamePlaceholder': 'आफ्नो पूरा नाम लेख्नुहोस्',
    'checkout.phoneNumber': 'फोन नम्बर',
    'checkout.phonePlaceholder': '१०-अङ्कको फोन नम्बर',
    'checkout.deliveryAddress': 'डेलिभरी ठेगाना',
    'checkout.addressPlaceholder': 'घर/फ्ल्याट नं., सडक, क्षेत्र',
    'checkout.cityDistrict': 'सहर / जिल्ला',
    'checkout.cityPlaceholder': 'जस्तै: काठमाडौं, ललितपुर',
    'checkout.landmark': 'ल्यान्डमार्क (वैकल्पिक)',
    'checkout.landmarkPlaceholder': 'सजिलो डेलिभरीका लागि नजिकको चिनारी',
    'checkout.deliveryNotes': 'डेलिभरी नोट (वैकल्पिक)',
    'checkout.notesPlaceholder': 'डेलिभरीका लागि विशेष निर्देशन',
    'checkout.paymentMethod': 'भुक्तानी विधि',
    'checkout.cashOnDelivery': 'क्यास अन डेलिभरी',
    'checkout.payOnDelivery': 'अर्डर पुगेपछि भुक्तानी गर्नुहोस्',
    'checkout.orderFailed': 'अर्डर असफल',
    'checkout.placingOrder': 'अर्डर राख्दैछ...',
    'checkout.placeOrder': 'अर्डर राख्नुहोस्',
    'checkout.orderSummary': 'अर्डर सारांश',
    'checkout.qty': 'परिमाण',
    'checkout.subtotal': 'उप-जम्मा',
    'checkout.deliveryFee': 'डेलिभरी शुल्क',
    'checkout.breakdownByFarm': 'फार्म अनुसार विवरण:',
    'checkout.beyondLimit': 'केही वस्तु डेलिभरी हुन सक्दैन (४० किमि सीमा बाहिर)',
    'checkout.total': 'जम्मा',
    'checkout.includingDelivery': 'डेलिभरी शुल्क सहित',
    'checkout.deliveryLocationRequired': 'डेलिभरी स्थान आवश्यक छ',
    'checkout.removeBeyondLimit': 'अगाडि बढ्न ४० किमि बाहिरका वस्तु हटाउनुहोस्',
    'checkout.payOnReceive': 'अर्डर प्राप्त गर्दा भुक्तानी गर्नुहोस्',
    'checkout.deliveryPricing': 'डेलिभरी मूल्य निर्धारण',
    'checkout.deliveryPricingRule': 'प्रति १० किमिमा रु ५० (माथि गोलाइन्छ)',
    'products.location.permissionDenied': 'स्थान अनुमति अस्वीकृत भयो। कृपया अनुमति दिनुहोस् वा म्यानुअली लेख्नुहोस्।',
    'products.location.unableDetermine': 'तपाईंको स्थान पत्ता लगाउन सकिएन। कृपया म्यानुअली लेख्नुहोस्।',
    'products.location.timeout': 'स्थान अनुरोध समय समाप्त भयो। फेरि प्रयास गर्नुहोस् वा म्यानुअली लेख्नुहोस्।',
    'products.location.failedGet': 'स्थान प्राप्त गर्न असफल। कृपया म्यानुअली लेख्नुहोस्।',
    'products.location.validCoordinates': 'मान्य निर्देशाङ्क लेख्नुहोस्',
    'products.location.latitudeRange': 'अक्षांश -९० देखि ९० बीच हुनुपर्छ',
    'products.location.longitudeRange': 'देशान्तर -१८० देखि १८० बीच हुनुपर्छ',
    'products.location.requiredTitle': '📍 स्थान आवश्यक',
    'products.location.setTitle': 'आफ्नो स्थान सेट गर्नुहोस्',
    'products.location.requiredDesc': 'उत्पादन हेर्न कृपया स्थान सेट गर्नुहोस्। यसले नजिकका फार्म देखाउन र सही डेलिभरी शुल्क गणना गर्न मद्दत गर्छ।',
    'products.location.setDesc': 'डेलिभरी शुल्क गणना र तपाईंकै क्षेत्रका उत्पादन देखाउन हामीलाई स्थान चाहिन्छ।',
    'products.addingToCart': 'कार्टमा थपिँदैछ...',
    'products.location.getting': 'स्थान लिँदैछ...',
    'products.location.allowAccess': 'स्थान पहुँच अनुमति दिनुहोस्',
    'products.location.enterManually': 'स्थान म्यानुअली लेख्नुहोस्',
    'products.location.storedLocally': 'तपाईंको स्थान स्थानीय रूपमा सुरक्षित हुन्छ र डेलिभरी गणनाका लागि मात्र प्रयोग हुन्छ।',
    'products.location.latitude': 'अक्षांश',
    'products.location.longitude': 'देशान्तर',
    'products.location.addressOptional': 'ठेगाना (वैकल्पिक)',
    'products.location.tip': 'सुझाव: Google Maps मा right-click गरेर "What\'s here?" छान्दा निर्देशाङ्क पाउन सकिन्छ।',
    'products.location.setLocation': 'स्थान सेट गर्नुहोस्',
    'products.rateProduct': 'मूल्याङ्कन गर्नुहोस्',
    'products.rateQuestion': 'यो उत्पादनलाई कसरी मूल्याङ्कन गर्नुहुन्छ?',
    'products.rating.tapToRate': 'मूल्याङ्कनका लागि स्टार फल थिच्नुहोस्',
    'products.rating.1': 'ताजा छैन 😕',
    'products.rating.2': 'ठिकै छ 🙂',
    'products.rating.3': 'स्वादिलो 😋',
    'products.rating.4': 'धेरै स्वादिलो 😍',
    'products.rating.5': 'फार्मको एकदम ताजा! 🤤',
    'products.writeReviewOptional': 'समीक्षा लेख्नुहोस् (वैकल्पिक)',
    'products.reviewPlaceholder': 'यस उत्पादनको अनुभव साझा गर्नुहोस्...',
    'products.signInToRate': 'मूल्याङ्कन पठाउन साइन इन गर्नुहोस्',
    'products.submitRating': 'मूल्याङ्कन पठाउनुहोस्',
    'products.by': 'लेखक',
    'products.watchVideo': 'भिडियो हेर्नुहोस्',
    'products.comments': 'टिप्पणी',
    'products.commentsTitle': 'टिप्पणीहरू',
    'products.addComment': 'टिप्पणी थप्नुहोस्...',
    'products.noComments': 'अहिलेसम्म टिप्पणी छैन। पहिलो बन्नुहोस्!',
    'products.organic': 'अर्गानिक',
    'products.story': 'कथा',
    'products.stories': 'कथाहरू',
    'products.rateThisProduct': 'यो उत्पादन मूल्याङ्कन गर्नुहोस्',
    'products.rate': 'रेट',
    'products.sort.newest': 'नयाँ आगमन',
    'products.sort.priceLow': 'मूल्य: कमदेखि धेरै',
    'products.sort.priceHigh': 'मूल्य: धेरैदेखि कम',
    'products.sort.distance': 'दूरी: नजिकको',
    'products.sort.name': 'नाम: A-Z',
    'products.deliveryLocationSet': 'डेलिभरी स्थान सेट भयो',
    'products.setLocationBetter': '📍 राम्रो अनुभवका लागि स्थान सेट गर्नुहोस्',
    'products.showingWithin': 'भित्रका फार्म देखाइँदैछ',
    'products.accurateDeliveryAndNearby': 'सही डेलिभरी शुल्क र नजिकका उत्पादन हेर्नुहोस्',
    'products.maxDistance': 'अधिकतम दूरी:',
    'products.allProducts': 'सबै उत्पादनहरू',
    'products.showing': 'देखाइँदैछ',
    'products.of': 'मध्ये',
    'products.products': 'उत्पादनहरू',
    'products.search': 'खोज्नुहोस्...',
    'products.noProductsHint': 'तपाईंले खोजेको भेट्न फिल्टर वा खोजी शब्द परिवर्तन गरेर हेर्नुहोस्',
    'products.clearAllFilters': 'सबै फिल्टर हटाउनुहोस्',
    'delivery.error.loadData': 'डेटा लोड गर्न असफल',
    'delivery.error.updateAvailability': 'उपलब्धता अपडेट गर्न असफल',
    'delivery.error.updateStatus': 'स्थिति अपडेट गर्न असफल',
    'delivery.error.updateLocation': 'स्थान अपडेट गर्न असफल। कृपया स्थान पहुँच अनुमति दिनुहोस्।',
    'delivery.tab.dashboard': 'ड्यासबोर्ड',
    'delivery.tab.assignments': 'असाइनमेन्टहरू',
    'delivery.tab.profile': 'प्रोफाइल',
    'delivery.welcomeBack': 'फेरि स्वागत छ',
    'delivery.welcomeDesc': 'असाइनमेन्ट ट्र्याक गर्नुहोस्, उपलब्धता व्यवस्थापन गर्नुहोस् र डेलिभरी समयमै राख्नुहोस्।',
    'delivery.setUnavailable': 'अनुपलब्ध बनाउनुहोस्',
    'delivery.setAvailable': 'उपलब्ध बनाउनुहोस्',
    'delivery.assignmentDistanceNote': 'असाइनमेन्टहरू ५० किमि भित्र दूरीका आधारमा पठाइन्छन्',
    'delivery.updateLocation': 'स्थान अपडेट',
    'delivery.pending': 'पेन्डिङ',
    'delivery.active': 'सक्रिय',
    'delivery.completed': 'सम्पन्न',
    'delivery.earnings': 'आम्दानी',
    'delivery.todaySummary': 'आजको सारांश',
    'delivery.deliveriesToday': 'आजका डेलिभरी',
    'delivery.earningsToday': 'आजको आम्दानी',
    'delivery.overallStats': 'समग्र तथ्याङ्क',
    'admin.tab.overview': 'सारांश',
    'admin.tab.orders': 'अर्डरहरू',
    'admin.tab.users': 'प्रयोगकर्ताहरू',
    'admin.tab.farmerApprovals': 'किसान स्वीकृतिहरू',
    'admin.tab.topProducts': 'शीर्ष उत्पादनहरू',
    'admin.tab.analytics': 'विश्लेषण',
    'admin.refreshData': 'डेटा रिफ्रेस',
    'admin.administrator': 'प्रशासक',
    'admin.updatedAt': 'अपडेट गरिएको',
    'productDetails.invalidId': 'अवैध उत्पादन आईडी।',
    'productDetails.unableOpen': 'उत्पादन खोल्न सकिएन',
    'productDetails.notFound': 'उत्पादन भेटिएन।',
    'productDetails.loadFailed': 'उत्पादन विवरण लोड गर्न असफल भयो।',
    'productDetails.unavailable': 'यो उत्पादन उपलब्ध छैन।',
    'productDetails.backToProducts': 'उत्पादन सूचीमा फर्कनुहोस्',
    'productDetails.noDescription': 'यस उत्पादनको विवरण हाल उपलब्ध छैन।',
    'productDetails.reviews': 'समीक्षा',
    'productDetails.farmer': 'किसान',
    'productDetails.farm': 'फार्म',
    'productDetails.kmAway': 'किमि टाढा',
    'productDetails.addToCart': 'कार्टमा थप्नुहोस्',
    'productDetails.customerReviews': 'ग्राहक समीक्षा',
    'productDetails.noReviews': 'अहिलेसम्म समीक्षा छैन। पहिलो मूल्याङ्कन गर्ने व्यक्ति बन्नुहोस्।',
    'discover.loadingProducts': 'उत्पादनहरू लोड हुँदैछन्',
    'discover.freshProducts': 'ताजा उत्पादनहरू',
    'discover.noProductsYet': 'अहिलेसम्म उत्पादन छैन',
    'discover.description': 'यो ल्यान्डिङ नेभिगेसनबाट उत्पादन हेर्न समर्पित पृष्ठ हो। छिटो हेर्नुहोस्, त्यसपछि फिल्टर र स्थान-आधारित डेलिभरी विवरणका लागि पूर्ण उत्पादन पृष्ठ खोल्नुहोस्।',
    'discover.noProductsAvailable': 'अहिले कुनै उत्पादन उपलब्ध छैन।',
    'discover.buyNow': 'अहिल्यै किन्नुहोस्',
    'consumer.notAssigned': 'नियुक्त छैन',
    'consumer.pickedUp': 'उठाइयो',
    'consumer.inTransit': 'बाटोमा',
    'consumer.welcomeTitle': 'उपभोक्ता पृष्ठमा स्वागत छ',
    'consumer.hello': 'नमस्ते',
    'consumer.deliveryInfo': 'डेलिभरी जानकारी',
    'consumer.viewAllOrders': 'सबै अर्डर हेर्नुहोस्',
    'consumer.noDeliveryUpdates': 'अहिलेसम्म डेलिभरी अपडेट छैन।',
    'consumer.partner': 'पार्टनर',
    'consumer.partnerNotAssigned': 'पार्टनर नियुक्त छैन',
  },
};

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

const getSavedLanguage = (): Language => {
  if (typeof window === 'undefined') {
    return 'en';
  }

  const stored = window.localStorage.getItem(STORAGE_KEY);
  return stored === 'ne' ? 'ne' : 'en';
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(getSavedLanguage);

  useEffect(() => {
    window.localStorage.setItem(STORAGE_KEY, language);
    document.documentElement.lang = language === 'ne' ? 'ne' : 'en';
  }, [language]);

  const setLanguage = useCallback((nextLanguage: Language) => {
    setLanguageState(nextLanguage);
  }, []);

  const toggleLanguage = useCallback(() => {
    setLanguageState((previousLanguage) => (previousLanguage === 'en' ? 'ne' : 'en'));
  }, []);

  const t = useCallback(
    (key: string, fallback?: string) => {
      return translations[language][key] ?? fallback ?? key;
    },
    [language]
  );

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      toggleLanguage,
      t,
    }),
    [language, setLanguage, toggleLanguage, t]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used inside a LanguageProvider');
  }
  return context;
};
